MIC.AseanTalentSearch.Web/Areas/Admin/Models/User/ClaimData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
{
    public static class ClaimData
    {
        public static List<string> UserClaims { get; set; } = new List<string> { "Instructor Admin", "Instructor Staff"};
    }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Models/User/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
{
    public class EditUserViewModel
    {
        public long Id { get; set; }
        [Required]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public MultiSelectList ApplicationRoles { get; set; }
        [Display(Name = "Role")]
        public IList<long> SelectedRoles { get; set; }
        public List<SelectListItem> UserClaims { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Models/User/InstructorGrid.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
{
    public class InstructorGrid
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public int? UniversityId { get; set; }
        public string University { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsStaff { get; set; }
        public IList<string> ApplicationRoles { get; set; }
        public bool IsActive { get; set; }
        
        public IList<long> SelectedRoles { get; set; }
        public List<SelectListItem> UserClaims { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Models/User/UserGrid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MIC.AseanTalentSearch.Web.Models;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
{
    public class UserGrid
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public IList<string> ApplicationRoles { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Models/User/UserViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
{
    public class UserViewModel
    {
        public long Id { get; set; }
        [Required]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        [Required]
        public string ConfirmPassword { get; set; }
        [Required]
        public string Email { get; set; }
        public MultiSelectList ApplicationRoles { get; set; }
        [Display(Name = "Role")]
        public IList<long> SelectedRoles { get; set; }

        [Display(Name = "User Claims")]
        public List<SelectListItem> UserClaims { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Models/AccountViewModels/ExternalLoginConfirmationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Models.AccountViewModels
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Role { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Models/AccountViewModels/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Models.AccountViewModels
{
    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Models/AccountViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MIC.AseanTalentSearch.Web.Models.AccountViewModels
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"^[A-Za-z0-9\[\]/!$%^&*()\-_+{};:'£@#.?]*$", ErrorMessage = "Password do not allow space")]
        public string Password { get; set; }

        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm password")]
        //[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        //public string ConfirmPassword { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
        
        //public string Role { get; set; }

    }
}

MIC.AseanTalentSearch.Web/Models/AccountViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Models.AccountViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [RegularExpression(@"^[A-Za-z0-9\[\]/!$%^&*()\-_+{};:'£@#.?]*$", ErrorMessage = "Password do not allow space")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
        [Required]
        public string Role { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Models/AccountViewModels/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIC.AseanTalentSearch.Web.Models.AccountViewModels
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [RegularExpression(@"^[A-Za-z0-9\[\]/!$%^&*()\-_+{};:'£@#.?]*$", ErrorMessage = "Password do not allow space")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MIC.AseanTalentSearch.Web.Areas.Admin.Models;
using MIC.AseanTalentSearch.Web.Areas.Admin.Models.User;
using MIC.AseanTalentSearch.Web.Controllers;
using MIC.AseanTalentSearch.Web.EF;
using MIC.AseanTalentSearch.Web.Models;
using MIC.AseanTalentSearch.Web.Models.AccountViewModels;
using MIC.AseanTalentSearch.Web.Services;
using Sakura.AspNetCore;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;
        private readonly string _externalCookieScheme;

        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager, SignInManager<ApplicationUser> signInManager,
            IOptions<IdentityCookieOptions> identityCookieOptions,
            IEmailSender emailSender,
            ISmsSender smsSender,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _externalCookieScheme = identityCookieOptions.Value.ExternalCookieAuthenticationScheme;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }

        public async Task<IActionResult> Index(int?page,string search)
        {
            int pageSize = 10;
            int pageIndex = page ?? 1;

          
            var data = await _userManager.Users.Select(m => new UserGrid
            {
                Id = m.Id,
                Email = m.Email,
                Username = m.UserName,
                ApplicationRoles = _roleManager.Roles.Where(r=>m.Roles.Select(t=>t.RoleId).Contains(r.Id)).Select(n=>n.Name).ToList()
            }).ToListAsync();

            if (!string.IsNullOrEmpty(search))
            {
               data= data.Where(x => x.Username.ToUpper().IndexOf(search.ToUpper()) >= 0).ToList();
            }
            return View(data.OrderBy(x=>x.Username).ToPagedList(pageSize, pageIndex));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            UserViewModel model = new UserViewModel();
            model.UserClaims = ClaimData.UserClaims.Select(c => new SelectListItem
            {
                Text = c,
                Value = c
            }).ToList();

            var applicationRoles = await _roleManager.Roles.Select(a => new {RoleId = a.Id, RoleName = a.Name}).ToListAsync();
            model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName");
            model.SelectedRoles = new List<long>();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserViewModel model, params string[] selectedRoles)
        {
            var applicationRoles = await _roleManager.Roles.Select(a => new { RoleId = a.Id, RoleName = a.Name }).ToListAsync();
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    EmailConfirmed = true
                };

                List<SelectListItem> userClaims = model.UserClaims.Where(c => c.Selected).ToList();
                foreach (var claim in userClaims)
                {
                    user.Claims.Add(new IdentityUserClaim<long>
                    {
                        ClaimType = claim.Value,
                        ClaimValue = claim.Value
                    });
                }

                // Then create:
                var adminresult = await _userManager.CreateAsync(user, model.Password);
                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var selectedRolesName = await 
                            _roleManager.Roles.Where(m => selectedRoles.Contains(m.Id.ToString())).Select(m => m.Name).ToListAsync();
                        var result = await _userManager.AddToRolesAsync(user, selectedRolesName);
                        if (!result.Succeeded)
                        {
                            foreach (IdentityError error in result.Errors)
                            {
                                ModelState.AddModelError("", $"Error code: {error.Code}, Description: {error.Description}");
                            }
                            model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName",selectedRoles);
                            return View();
                        }
                    }
                }
                else
                {
                    foreach (IdentityError error in adminresult.Errors)
                    {
                        ModelState.AddModelError("", $"Error code: {error.Code}, Description: {error.Description}");
                    }

                    model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName", selectedRoles);
                    return View();
                }
                return RedirectToAction("Index");
            }
            model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName", selectedRoles);
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var applicationRoles = await _roleManager.Roles.Select(a => new { RoleId = a.Id, RoleName = a.Name }).ToListAsync();
            var userRolesName = await _userManager.GetRolesAsync(user);
            var userRolesId = await _roleManager.Roles.Where(m => userRolesName.Contains(m.Name)).Select(m => m.Id).ToListAsync();
            var claims = await _userManager.GetClaimsAsync(user);
            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName"),
                SelectedRoles = userRolesId ?? (userRolesId = new List<long>()),
                UserClaims = ClaimData.UserClaims.Select(c => new SelectListItem
                {
                    Text = c,
                    Value = c,
                    Selected = claims.Any(x => x.Value == c)
                }).ToList()
        };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditUserViewModel model, params string[] selectedRoles)
        {
            var applicationRoles = await _roleManager.Roles.Select(a => new { RoleId = a.Id, RoleName = a.Name }).ToListAsync();
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(id);
                if (user == null)
                {
                    return NotFound();
                }

                user.Email = model.Email;

                await ModifyUserClaim(model, user);
                var userRolesName = await _userManager.GetRolesAsync(user);
                selectedRoles = selectedRoles ?? new string[] { };
                var selectedRolesName = await
                           _roleManager.Roles.Where(m => selectedRoles.Contains(m.Id.ToString())).Select(m => m.Name).ToListAsync();
                var result = await _userManager.AddToRolesAsync(user,
                    selectedRolesName.Except(userRolesName).ToArray<string>());      

                if (!result.Succeeded)
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", $"Error code: {error.Code}, Description: {error.Description}");
                    }
                    model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName", selectedRoles);
                    return View();
                }
                result = await _userManager.RemoveFromRolesAsync(user,
                    userRolesName.Except(selectedRolesName).ToArray<string>());
                if (!result.Succeeded)
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", $"Error code: {error.Code}, Description: {error.Description}");
                    }
                    model.ApplicationRoles = new MultiSelectList(applicationRoles, "RoleId", "RoleName", selectedRoles);
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "Confirm Email";
    Layout = "_AccountLayout";
}

<h2>@ViewData["Title"].</h2>
<div>
    <p>
        Thank you for confirming your email. Please <a asp-controller="Account" asp-action="Login">Click here to Log in</a>.
    </p>
</div>

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/Delete.cshtml
@model ApplicationUser

@{
    ViewData["Title"] = "Delete Role";
}

@section heading {
    <h1>Role</h1>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <p class="lead text-danger">Are you sure you want to delete @Model.UserName?</p>
                <form asp-action="Delete">
                    <div class="form-actions no-color">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-default" />
                    </div>
                </form>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/Edit.cshtml
@using MIC.AseanTalentSearch.Web.Areas.Admin.Models.User
@model EditUserViewModel
@{
    ViewData["Title"] = "Update User";
}
@section heading{
    <h1>User</h1>
}
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <form asp-action="Edit">
                    <div class="form-horizontal">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="Email" class="col-md-2 control-label">@T.T("Admin.Email")</label>
                            <div class="col-md-10">
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="UserClaims" class="col-md-2 control-label">@T.T("Admin.UserClaims")</label>
                            <div class="col-md-10">
                                @for (int i = 0; i < Model.UserClaims.Count; i++)
                                {
                                    <div class="col-md-4">
                                        
                                        <label class="checkbox" asp-for="@Model.UserClaims[i].Selected"><input type="checkbox" asp-for="@Model.UserClaims[i].Selected" />@Model.UserClaims[i].Text</label>
                                        <input type="hidden" asp-for="@Model.UserClaims[i].Value" />
                                        <input type="hidden" asp-for="@Model.UserClaims[i].Text" />
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="SelectedRoles" class="col-md-2 control-label">@T.T("Admin.Role")</label>
                            <div class="col-md-10">
                                <select class="selectpicker form-control" asp-for="SelectedRoles" asp-items="@Model.ApplicationRoles" data-live-search="true"></select>
                                <span asp-validation-for="SelectedRoles" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="@T.T("Admin.Save")" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>


<div>
    <a asp-action="Index">Back to list</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/ExternalLoginConfirmation.cshtml
@model ExternalLoginConfirmationViewModel
@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"].</h2>
<h3>Associate your @ViewData["LoginProvider"] account.</h3>

<form asp-controller="Account" asp-action="ExternalLoginConfirmation" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
    <h4>Association Form</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <p class="text-info">
        You've successfully authenticated with <strong>@ViewData["LoginProvider"]</strong>.
        Please enter an email address for this site below and click the Register button to finish
        logging in.
    </p>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/ExternalLoginFailure.cshtml
@{
    ViewData["Title"] = "Login Failure";
}

<header>
    <h2>@ViewData["Title"].</h2>
    <p class="text-danger">Unsuccessful login with service.</p>
</header>

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/ForgotPassword.cshtml
@model ForgotPasswordViewModel
@{
    ViewData["Title"] = "Forgot your password?";
    Layout = "_AccountLayout";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Account" asp-action="ForgotPassword" method="post" class="form-horizontal">
    <h4>Enter your email.</h4>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/ForgotPasswordConfirmation.cshtml
@{
    ViewData["Title"] = "Forgot Password Confirmation";
    Layout = "_AccountLayout";
}

<h2>@ViewData["Title"].</h2>
<p>
    Please check your email to reset your password.
</p>

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/Index.cshtml
@model IEnumerable<MIC.AseanTalentSearch.Web.Areas.Admin.Models.User.UserGrid>
@{
    ViewData["Title"] = "List User";
}
@section heading{
    <h1>User</h1>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>

                <div class="box-tools">

                </div>
            </div>
            <div class="box-operation clearfix" style="border-bottom: 1px solid #eeeeea">
                <a asp-action="Create" class="btn btn-primary"><i class='fa fa-plus'></i> @T.T("Admin.Create")</a>
                <form method="get" class="pull-right">
                    @*<div class="form-group">

                                <input type="text" class="form-control" name="search"/>


                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>

                    </div>*@
                    <div class="input-group" style="width:240px;">
                        <input type="text" class="form-control" name="search" placeholder="Username" aria-describedby="basic-addon1">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                            @*<button class="btn btn-secondary" type="button">Go!</button>*@
                        </span>
                    </div>
                </form>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                @T.T("Admin.Name")
                            </th>
                            <th>
                                @T.T("Admin.Email")
                            </th>
                            <th>
                                @T.T("Admin.ApplicationRoles")
                            </th>
                            <th class="text-right" style="padding-right:100px;">@T.T("Admin.Action")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(m => item.Username)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => item.Email)
                                </td>
                                <td>
                                    @(String.Join(", ",item.ApplicationRoles))
                                </td>
                                <td class="text-right">
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info"><i class="fa fa-pencil"></i> @T.T("Admin.Edit")</a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa fa-trash"></i> @T.T("Admin.Delete")</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="text-center">
                    <ul class="pagination">
                        <pager />
                    </ul>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

MIC.AseanTalentSearch.Web/Areas/Admin/Views/User/Login.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@model LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager

@{
    Layout = "_AccountLayout";
    ViewData["Title"] = "Log in";
}

<form asp-controller="User" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group has-feedback">
        <input asp-for="Email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group has-feedback">
        <input asp-for="Password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-xs-8">
            <div class="checkbox icheck">
                <label asp-for="RememberMe">
                    <input asp-for="RememberMe" />
                    Remember me?
                </label>
            </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Login</button>
        </div>
        <!-- /.col -->
    </div>
</form>
<a asp-action="ForgotPassword">Forgot password?</a>

@section scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}