MIC.AseanTalentSearch.Web/Areas/Admin/Controllers/UniversityController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MIC.AseanTalentSearch.Web.EF;
using Microsoft.EntityFrameworkCore;
using Sakura.AspNetCore;
using Microsoft.AspNetCore.Http;
using MIC.AseanTalentSearch.Web.Settings;
using MIC.AseanTalentSearch.Web.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace MIC.AseanTalentSearch.Web.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class UniversityController : Controller
    {
        private readonly AseanTalentSearchContext _context;
        private readonly PathUpLoad _pathUpLoad;
        private readonly IImageService _imageService;
        private IHostingEnvironment _env;

        public UniversityController(AseanTalentSearchContext context, IImageService imageService, IHostingEnvironment env, IOptions<PathUpLoad> pathUpload)
        {
            _context = context;
            _imageService = imageService;
            _env = env;
            _pathUpLoad = pathUpload.Value;
        }


        public IActionResult FindProvinceByCountryId(int? id)
        {
            List<SelectListItem> states = new List<SelectListItem>();
            if (id != null)
            {
                foreach (var item in _context.Location.Where(m => m.ParentId == id))
                {
                    states.Add(new SelectListItem { Text = item.Name, Value = item.Id.ToString() });
                }
            }
            return Json(states.OrderBy(x=>x.Text));
        }

        [HttpGet]
        public IActionResult Index(int? page, string search)
        {
            search = search ?? "";
            int pageIndex = page ?? 1;
            var rs = _context.University.Include(x => x.Location)
                .Where(x=>x.Name.Contains(search))
                .OrderByDescending(x => x.ActiveStatus).ThenBy(x => x.Name);
             var model = rs.ToPagedList(10, pageIndex);

            foreach (var item in model)
            {
                if (item.Location.ParentId != null)
                {
                    item.Location = _context.Location.Find(item.Location.ParentId.Value);
                }
            }

            return View(model);
        }

        public ActionResult Create()
        {
            var location = _context.Location.OrderBy(x => x.Name).Where(m => m.Type == 1).ToList();
            ViewBag.Locations = new SelectList(location, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(University university, IFormFile logo, int province)
        {
            List<Location> location = null;
            if (ModelState.IsValid)
            {
                if (province == 0)
                {
                    ModelState.AddModelError("", "Please select nation and province");
                    location = _context.Location.Where(m => m.Type == 1).ToList();
                    ViewBag.Locations = new SelectList(location, "Id", "Name");
                    return View(university);
                }

                if (!await _context.University.Where(x => x.Name.Equals(university.Name)).AnyAsync())
                {

                    AspNetUsers currentUser = _context.AspNetUsers.Where(x => x.UserName.Equals(User.Identity.Name)).FirstOrDefault();
                    university.CreatedBy = currentUser.Id;
                    university.CreatedDate = DateTime.Now;
                    string imagePath = String.Empty;

                    university.LocationId = province;

                    if (university.ActiveStatus.Value)
                    {
                        university.ActiveBy = currentUser.Id;
                        university.ActiveDate = DateTime.Now;
                    }

                    //validate and upload logo
                    if (logo != null)
                    {
                        if (_imageService.Validate(logo))
                        {
                            try
                            {
                                imagePath = await _imageService.SaveAsync(logo, _pathUpLoad.FrontImage);
                                university.Logo = _pathUpLoad.FrontImage + imagePath;
                            }
                            catch (Exception e)
                            {
                                ModelState.AddModelError("", "Sorry an error occurred saving to the database, please try again");
                                location = _context.Location.Where(m => m.Type == 1).ToList();
                                ViewBag.Locations = new SelectList(location, "Id", "Name");
                                return View(university);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "The logo file must be gif, png, jpeg or jpg and less than 2MB in size");
                            location = _context.Location.Where(m => m.Type == 1).ToList();
                            ViewBag.Locations = new SelectList(location, "Id", "Name");
                            return View(university);
                        }


                    }

                    try
                    {
                        await _context.University.AddAsync(university);
                        _context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Sorry an error occurred saving to the database, please try again");
                    }


                }
                else
                {
                    ModelState.AddModelError("", "University name is exist. Please try another!");
                }
            }
            location = _context.Location.Where(m => m.Type == 1).ToList();
            ViewBag.Locations = new SelectList(location, "Id", "Name");
            return View(university);
        }


        public IActionResult Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var university = _context.University.Include(m => m.Location).Where(x => x.Id == id).FirstOrDefault();
            if (university == null)
            {
                return NotFound();
            }

            int? currentLocationId = university.LocationId;
            int nationIdSelected = 0;
            int provinceIdSelected = 0;


            if (currentLocationId != null)
            {
                nationIdSelected = university.Location.ParentId ?? 0;
                provinceIdSelected = currentLocationId ?? 0;
            }

            var nationLocations = _context.Location.OrderBy(x => x.Name).Where(m => m.Type == 1).ToList();
            ViewBag.NationLocations = new SelectList(nationLocations, "Id", "Name", nationIdSelected);

            var provinceLocations = _context.Location.OrderBy(x=>x.Name).Where(m => m.ParentId == nationIdSelected).ToList();
            ViewBag.ProvinceLocations = new SelectList(provinceLocations, "Id", "Name", provinceIdSelected);



            return View(university);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, University university, IFormFile logo, int province)
        {
            if (id != university.Id)
            {
                return NotFound();
            }

            ///for location select option
            int? currentLocationId = university.LocationId;
            int nationIdSelected = 0;
            int provinceIdSelected = 0;


            if (currentLocationId != null)
            {
                nationIdSelected = university.Location.ParentId ?? 0;
                provinceIdSelected = currentLocationId ?? 0;
            }

            List<Location> nationLocations = _context.Location.Where(m => m.Type == 1).ToList();
            ViewBag.NationLocations = new SelectList(nationLocations, "Id", "Name", nationIdSelected);

            List<Location> provinceLocations = _context.Location.Where(m => m.ParentId == nationIdSelected).ToList();
            ViewBag.ProvinceLocations = new SelectList(provinceLocations, "Id", "Name", provinceIdSelected);

            ///





            if (ModelState.IsValid)
            {
                if (province == 0)
                {
                    ModelState.AddModelError("", "Please select nation and province");

                    nationLocations = _context.Location.Where(m => m.Type == 1).ToList();
                    ViewBag.NationLocations = new SelectList(nationLocations, "Id", "Name", nationIdSelected);

                    provinceLocations = _context.Location.Where(m => m.ParentId == nationIdSelected).ToList();
                    ViewBag.ProvinceLocations = new SelectList(provinceLocations, "Id", "Name", provinceIdSelected);
                    return View(university);
                }
                if (!await _context.University.Where(x => x.Id != id && x.Name.Equals(university.Name)).AnyAsync())
                {
                    AspNetUsers currentUser = _context.AspNetUsers.Where(x => x.UserName.Equals(User.Identity.Name)).FirstOrDefault();
                    university.ModifiedBy = currentUser.Id;
                    university.ModifiedDate = DateTime.Now;
                    university.LocationId = province;

                    //check update logo
                    if (logo != null)
                    {
                        string imagePath = string.Empty;
                        if (_imageService.Validate(logo))
                        {
                            try
                            {

MIC.AseanTalentSearch.Web/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MIC.AseanTalentSearch.Web.EF;
using MIC.AseanTalentSearch.Web.Models;
using Sakura.AspNetCore;

namespace MIC.AseanTalentSearch.Web.Controllers
{
    public class UniversityController : BaseController
    {
        private AseanTalentSearchContext _context;

        public UniversityController(AseanTalentSearchContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetMajorByUniversity(int? uid, int ? elid)
        {
            if (!uid.HasValue|| !elid.HasValue)
                return Json(null);
            else
            {
                var model = _context.Major.Where(e => e.UniversityId == uid.Value&&e.EducationLevelId==elid).OrderBy(x=>x.Name);
                return Json(model);
            }
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var university = _context.University.Include(m=>m.Location).FirstOrDefault(m=>m.Id == id);
            ViewBag.StudentCount = _context.EducationHistory.Include(m => m.Candidate).ThenInclude(m => m.IdNavigation)
                .ThenInclude(m => m.AspNetUserRoles).ThenInclude(m => m.Role).Include(m => m.Major)
                .ThenInclude(m => m.University)
                .Where(m => m.Major.University.Id == id &&
                            m.Candidate.IdNavigation.AspNetUserRoles.Any(u => u.Role.Name == "Candidate"))
                .Select(m => m.CandidateId)
                .Distinct().Count();
            if (university == null)
            {
                return NotFound();
            }
            return View(university);
        }

        public async Task<IActionResult> List(int? page)
        {
            var data = await _context.University.Include(m => m.Location).OrderByDescending(m => m.ModifiedDate).Where(a => a.ActiveStatus == true).Select(
                 m => new HottestUniversityViewModel
                 {
                     University = m,
                     Location = m.Location
                 }).ToListAsync();
            foreach (var item in data)
            {
                item.StudentCount = GetNumberCandidate(item.University.Id);
            }
            int pageSize = 10;
            int pageIndex = page ?? 1;
            var dataPager = data.ToPagedList(pageSize, pageIndex);
            return View("Hottest", dataPager);
        }


        public int? GetNumberCandidate(int UId)
        {
            var rs = from major in _context.Major
                     join eh in _context.EducationHistory on major.Id equals eh.MajorId
                     join can in _context.Candidate on eh.CandidateId equals can.Id
                     where major.UniversityId == UId
                     select new
                     {
                         id = eh.Candidate.Id,
                         name = eh.Candidate.FullName
                     };
            return rs.GroupBy(m => m.id).Count();
        }
    }
}

MIC.AseanTalentSearch.Web/Views/University/Hottest.cshtml
@model Sakura.AspNetCore.IPagedList<HottestUniversityViewModel>
@{
    ViewData["Title"] = "Universities";
}
@await Component.InvokeAsync("SubJobSearchForm")

@*<section id="hottest-list">
    <div class="container">
        <h3 class="text-center text-uppercase"> @ViewData["Title"]</h3>
        <hr class="text-center"/>
        <div id="job-search-result" class="box box-solid box-default">
            <div class="box-body">
                @if (Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <div class="job-item">
                            <div class="relative">
                                <div class="row">
                                    <div class="col-xs-3 col-sm-3 col-lg-2">
                                        <div class="logo job-search__logo">
                                            <a class="job-logo" asp-controller="University" asp-action="Detail" asp-route-id="@item.University.Id">
                                                @{
                                                    var logoSrc = item.University.Logo ?? Url.Content("~/images/noimage.png");
                                                }
                                                <img title="@(item.University.Name??"No name")" class="img-responsive" src="@logoSrc">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-xs-9 col-sm-9 col-lg-10">
                                        <a asp-controller="University" asp-action="Detail" asp-route-id="@item.University.Id" title="@(item.University.Name)" class="relative">
                                            <div class="clearfix">
                                                <div class="pull-left">
                                                    <span>
                                                        <strong class="job-title"> @item.University.Name</strong>
                                                    </span>
                                                    <span class="address">@item.University.Address</span>
                                                </div>
                                                <div class="pull-right">
                                                    <span class="location">
                                                        @item.Location?.Name<br />
                                                    <span style="color:#3c8dbc">Students: @item.StudentCount</span>
                                                    </span>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="text-center">
                        <ul class="pagination">
                            <pager />
                        </ul>
                    </div>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                            No result found!
                        </div>
                    }
            </div>
            <!-- /.box-body -->
        </div>
    </div>
</section>*@
<section class="alljob-content-footer content-company">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h3 class="text-left title-header">@T.T("University.Universities")</h3>
                <div class="alljob-table">
                    <div class="table-responsive">
                        <table class="table table-condensed table-striped">
                            <tbody>
                                @if (Model.Any())
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="td_image">
                                                <a class="job-logo" asp-controller="University" asp-action="Detail" asp-route-id="@item.University.Id">
                                                <div class="td-img-content">
                                                    <img class="img-responsive" src="@item.University.Logo" />
                                                </div>
                                                </a>
                                            </td>
                                            <td class="text-left">
                                                <a class="job-logo" asp-controller="University" asp-action="Detail" asp-route-id="@item.University.Id">
                                                <p class="text-bold">@item.University.Name</p>
                                                </a>
                                                <p>
                                                    <em>@item.University.Address /</em>
                                                    <span>@item.Location.Name</span>
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    <i class="fa fa-user" aria-hidden="true"></i>
                                                    Student: @item.StudentCount
                                                </p>
                                            </td>
                                            @*<td>
                                                <a class="btn btn-orange btn-fill-horz" asp-controller="University" asp-action="Detail" asp-route-id="@item.University.Id">
                                                    View more
                                                </a>
                                            </td>*@
                                        </tr>

                                    }

                                    <tr class="pagination-table">
                                        <td colspan="4">
                                            <pager />
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    <tr class="alert alert-warning">
                                        <td colspan="4">
                                            <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                                            @T.T("Home.NoUniversityFound")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="text-center"></div>
                </div>
            </div>
            <div class="col-md-3">
                <p class="job-detail-header" style="text-transform:uppercase">
                    <i class="fa fa-square" aria-hidden="true"></i>
                    @T.T("Home.FeaturedJobs")
                </p>
                <div class="for-card owl-carousel owl-theme">
                    @await Component.InvokeAsync("FeaturedWork")
                </div>
            </div>
        </div>
    </div>
</section>