MIC.AseanTalentSearch.Web/Areas/Employer/Controllers/CompanyBenefitsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MIC.AseanTalentSearch.Web.EF;

namespace MIC.AseanTalentSearch.Web.Areas.Employer.Controllers {
    [Area("Employer")]
    [Authorize(Roles = "Employer")]
    public class CompanyBenefitsController: Controller {
        private readonly AseanTalentSearchContext _context;

        public CompanyBenefitsController(AseanTalentSearchContext context) {
            _context = context;
        }

        // GET: Employer/CompanyBenefits
        public async Task < IActionResult > Index(long companyId) {
            if (await _context.Company.FindAsync(companyId) == null) {
                return NotFound();
            }
            ViewData["CompanyId"] = companyId;
            return View(await _context.CompanyBenefit
                .Where(m => m.CompanyId == companyId)
                .Include(c => c.Benefit)
                .OrderBy(m => m.Benefit.Name)
                .ToListAsync());
        }

        // GET: Employer/CompanyBenefits/Create
        public async Task < IActionResult > Create(long companyId) {
            var company = await _context.Company.Include(m => m.CompanyBenefit).FirstOrDefaultAsync(m => m.Id == companyId);
            if (company == null) {
                return NotFound();
            }
            var benefits = await _context.Benefit
                .Where(m => company.CompanyBenefit.All(r => r.BenefitId != m.Id))
                .OrderBy(m => m.Name).ToListAsync();
            ViewData["BenefitId"] = new SelectList(benefits, "Id", "Name");
            return View(new CompanyBenefit() {
                CompanyId = companyId
            });
        }

        // POST: Employer/CompanyBenefits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task < IActionResult > Create(CompanyBenefit companyBenefit) {
            if (ModelState.IsValid) {
                if (companyBenefit.ActiveDate != null && companyBenefit.ActiveClosed != null && companyBenefit.ActiveClosed < companyBenefit.ActiveDate) {
                    ModelState.TryAddModelError("ActiveClosed", "ActiveClosed is small than ActiveDate !");
                } else {
                    _context.Add(companyBenefit);
                    await _context.SaveChangesAsync();

                    ModelState.AddModelError("Success", "Created successful !");
                    ViewData["CompanyId"] = companyBenefit.CompanyId;
                    return View("Index", await _context.CompanyBenefit
                        .Where(m => m.CompanyId == companyBenefit.CompanyId)
                        .Include(c => c.Benefit)
                        .OrderBy(m => m.Benefit.Name)
                        .ToListAsync());
                }

            }
            return BadRequest(ModelState);
        }

        // GET: Employer/CompanyBenefits/Edit/5
        public async Task < IActionResult > Edit(long companyId, int benefitId) {
            var companyBenefit = await _context.CompanyBenefit
                .Include(c => c.Benefit)
                .SingleOrDefaultAsync(m => m.CompanyId == companyId && m.BenefitId == benefitId);
            if (companyBenefit == null) {
                return NotFound();
            }
            return View(companyBenefit);
        }

        // POST: Employer/CompanyBenefits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task < IActionResult > Edit(CompanyBenefit companyBenefit) {
            if (ModelState.IsValid) {
                if (companyBenefit.ActiveDate != null && companyBenefit.ActiveClosed != null && companyBenefit.ActiveClosed < companyBenefit.ActiveDate) {
                    ModelState.TryAddModelError("ActiveClosed", "ActiveClosed is small than ActiveDate !");
                } else {
                    try {
                        _context.Update(companyBenefit);
                        await _context.SaveChangesAsync();
                        ModelState.AddModelError("Success", "Updated successful !");
                        return Ok(ModelState);
                    } catch (DbUpdateConcurrencyException) {
                        if (!CompanyBenefitExists(companyBenefit.CompanyId, companyBenefit.BenefitId)) {
                            return NotFound();
                        } else {
                            ModelState.AddModelError("Error", "Internal server error ..!");
                        }
                    }
                }

            }
            return BadRequest(ModelState);
        }

        // GET: Employer/CompanyBenefits/Delete/5
        public async Task < IActionResult > Delete(long companyId, int benefitId) {
            var companyBenefit = await _context.CompanyBenefit
                .Include(c => c.Benefit)
                .SingleOrDefaultAsync(m => m.CompanyId == companyId && m.BenefitId == benefitId);
            if (companyBenefit == null) {
                return NotFound();
            }

            return View(companyBenefit);
        }

        // POST: Employer/CompanyBenefits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task < IActionResult > DeleteConfirmed(long companyId, int benefitId) {
            var companyBenefit = await _context.CompanyBenefit.SingleOrDefaultAsync(m => m.CompanyId == companyId && m.BenefitId == benefitId);
            _context.CompanyBenefit.Remove(companyBenefit);
            await _context.SaveChangesAsync();

            ModelState.AddModelError("Success", "Deleted successful !");
            ViewData["CompanyId"] = companyId;
            return View("Index", await _context.CompanyBenefit
                .Where(m => m.CompanyId == companyId)
                .Include(c => c.Benefit)
                .OrderBy(m => m.Benefit.Name)
                .ToListAsync());
        }

        private bool CompanyBenefitExists(long companyId, int benefitId) {
            return _context.CompanyBenefit.Any(m => m.CompanyId == companyId && m.BenefitId == benefitId);
        }
    }
}

MIC.AseanTalentSearch.Web/Areas/Employer/Views/CompanyBenefits/Create.cshtml
@using MIC.AseanTalentSearch.Web.EF
@model MIC.AseanTalentSearch.Web.EF.CompanyBenefit

@{
    if (Context.Request.Headers["x-requested-with"] == "XMLHttpRequest") {Layout = null;}
}

<section class="animated fadeIn">
    <form asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Create" asp-route-companyId="@ViewBag.CompanyId" data-ajax="true" data-ajax-method="post" data-ajax-update="#Outer_CompanyBenefit" data-ajax-failure="$(this).displayValidation(xhr);notifyStatusCode(xhr);">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @await Html.PartialAsync("Partial/_ModelStatePartial")
                </div>
            </div>

            <input type="hidden" asp-for="CompanyId" />
            <input type="hidden" asp-for="ActiveBy" value="@User.Identity.Name" />
            <div class="form-group">
                <label asp-for="BenefitId" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="BenefitId" class="form-control" asp-items="ViewBag.BenefitId"></select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ActiveDate" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                    <input class="form-control datepicker" value="@string.Format("{0:d}",Model.ActiveDate)" onchange="$(this).next().val((moment($(this).val(), ['DD-MM-YYYY','MM-DD-YYYY']).format('YYYY-MM-DD')))"/>
                    <input asp-for="ActiveDate" type="hidden" />
                    <span asp-validation-for="ActiveDate" class="text-danger"></span>
                </div>
                <label asp-for="ActiveClosed" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                    <input class="form-control datepicker" value="@string.Format("{0:d}", Model.ActiveClosed)" onchange="$(this).next().val((moment($(this).val(), ['DD-MM-YYYY','MM-DD-YYYY']).format('YYYY-MM-DD')))"/>
                    <input asp-for="ActiveClosed" type="hidden" />
                    <span asp-validation-for="ActiveClosed" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ActiveStatus" class="col-md-2 control-label"></label>
                <div class="col-md-10 checkbox">
                    @Html.RadioButton("ActiveStatus", true, Model.ActiveStatus ?? false, new { @class = "" }) <span class="margin-r-5">Yes</span>
                    @Html.RadioButton("ActiveStatus", false, !Model.ActiveStatus ?? true, new { @class = "" }) <span class="margin-r-5">No</span>
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10 pull-right">
                    <button type="submit" class="btn btn-fill-horz btn-employer">Create</button>
                    <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Index" asp-route-companyId="@Model.CompanyId" class="btn btn-default btn-flat" 
                       data-ajax="true" data-ajax-method="get" data-ajax-update="#Outer_CompanyBenefit" style="margin-top:30px">Back to List</a>
                </div>
            </div>
        </div>
    </form>
</section>

@{
    await Html.RenderPartialAsync("_RegisterComponentScriptsPartial");
}

MIC.AseanTalentSearch.Web/Areas/Employer/Views/CompanyBenefits/Delete.cshtml
@model MIC.AseanTalentSearch.Web.EF.CompanyBenefit

@{
    if (Context.Request.Headers["x-requested-with"] == "XMLHttpRequest") { Layout = null; }
}

<div class="animated fadeIn">
    <dl class="dl-horizontal">
        <dd>
            <h3 class="text-danger">Are you sure you want to delete this?</h3>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Benefit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Benefit.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveStatus)
        </dt>
        <dd>
            @if (Model.ActiveStatus ?? false)
            {
                <span class="label label-success">Actived</span>
            }
            else
            {
                <span class="label label-warning">No actived</span>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveDate)
        </dt>
        <dd>
            @string.Format("{0:d}", Model.ActiveDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveClosed)
        </dt>
        <dd>
            @string.Format("{0:d}", Model.ActiveClosed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActiveBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @string.Format("{0:d}", Model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dd>
            <br/>
            <form asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Delete" asp-route-benefitId="@Model.BenefitId" asp-route-companyId="@Model.CompanyId" data-ajax="true" data-ajax-method="post" data-ajax-update="#Outer_CompanyBenefit" data-ajax-failure="$(this).displayValidation(xhr);notifyStatusCode(xhr);">
                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger btn-flat">Delete</button>
                    <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Index" asp-route-companyId="@Model.CompanyId" class="btn btn-default btn-flat" data-ajax="true" data-ajax-method="get" data-ajax-update="#Outer_CompanyBenefit">Back to List</a>
                </div>
            </form>
        </dd>
    </dl>
</div>

MIC.AseanTalentSearch.Web/Areas/Employer/Views/CompanyBenefits/Edit.cshtml
@using MIC.AseanTalentSearch.Web.EF
@model MIC.AseanTalentSearch.Web.EF.CompanyBenefit

@{
    if (Context.Request.Headers["x-requested-with"] == "XMLHttpRequest") { Layout = null; }
}

<section class="animated fadeIn">
    <form asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Edit" data-ajax="true" data-ajax-method="post" data-ajax-success="$(this).displayValidation(xhr);notifyStatusCode(xhr)" data-ajax-failure="$(this).displayValidation(xhr);notifyStatusCode(xhr)">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @await Html.PartialAsync("Partial/_ModelStatePartial")
                </div>
            </div>

            <input type="hidden" asp-for="BenefitId" />
            <input type="hidden" asp-for="CompanyId" />
            <input type="hidden" asp-for="ActiveBy" value="@User.Identity.Name" />
            <div class="form-group">
                <label asp-for="BenefitId" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input type="text" readonly="readonly" class="form-control" value="@Model.Benefit?.Name" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ActiveDate" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                    <input class="form-control datepicker" value="@string.Format("{0:d}",Model.ActiveDate)" onchange="$(this).next().val((moment($(this).val(), ['DD-MM-YYYY','MM-DD-YYYY']).format('YYYY-MM-DD')))" />
                    <input asp-for="ActiveDate" type="hidden" />
                    <span asp-validation-for="ActiveDate" class="text-danger"></span>
                </div>
                <label asp-for="ActiveClosed" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                    <input class="form-control datepicker" value="@string.Format("{0:d}", Model.ActiveClosed)" onchange="$(this).next().val((moment($(this).val(), ['DD-MM-YYYY','MM-DD-YYYY']).format('YYYY-MM-DD')))" />
                    <input asp-for="ActiveClosed" type="hidden" />
                    <span asp-validation-for="ActiveClosed" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ActiveStatus" class="col-md-2 control-label"></label>
                <div class="col-md-10 checkbox">
                    @Html.RadioButton("ActiveStatus", true, Model.ActiveStatus ?? false, new { @class = "" }) <span class="margin-r-5">Yes</span>
                    @Html.RadioButton("ActiveStatus", false, !Model.ActiveStatus ?? true, new { @class = "" }) <span class="margin-r-5">No</span>
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-fill-horz btn-employer">Update</button>
                    <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Index" asp-route-companyId="@Model.CompanyId" class="btn btn-default btn-flat"
                       data-ajax="true" data-ajax-method="get" data-ajax-update="#Outer_CompanyBenefit" style="margin-top:30px">Back to List</a>
                </div>
            </div>
        </div>
    </form>
</section>

@{
    await Html.RenderPartialAsync("_RegisterComponentScriptsPartial");
}

MIC.AseanTalentSearch.Web/Areas/Employer/Views/CompanyBenefits/Index.cshtml
@model IEnumerable<MIC.AseanTalentSearch.Web.EF.CompanyBenefit>
@{
    if (Context.Request.Headers["x-requested-with"] == "XMLHttpRequest") { Layout = null; }
}
@*<section class="animated fadeIn">
        @await Html.PartialAsync("Partial/_ModelStatePartial")
        <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Create" asp-route-companyId="@ViewBag.CompanyId" class="btn btn-info btn-flat" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit">Add new</a>
        @if (Model.Any())
        {
            <table class="table">
                <thead>
                <tr>
                    <th>@@</th>
                    <th>
                        @Html.DisplayNameFor(model => model.Benefit)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveStatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveClosed)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ModifiedDate)
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Edit" asp-route-benefitId="@item.BenefitId" asp-route-companyId="@item.CompanyId" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit"><i class="fa fa-pencil text-info margin-r-5"></i></a>
                            <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Delete" asp-route-benefitId="@item.BenefitId" asp-route-companyId="@item.CompanyId" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit"><i class="fa fa-trash-o text-danger margin-r-5"></i></a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Benefit.Name)
                        </td>
                        <td>
                            @if (item.ActiveStatus ?? false)
                            {
                                <span class="label label-success">Actived</span>
                            }
                            else
                            {
                                <span class="label label-warning">No actived</span>
                            }
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ActiveDate)
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ActiveClosed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ActiveBy)
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ModifiedDate)
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <h4 class="text-gray">No data ..</h4>
        }
    </section>*@

<section class="animated fadeIn">
    @await Html.PartialAsync("Partial/_ModelStatePartial")
    <a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Create" asp-route-companyId="@ViewBag.CompanyId" 
       class="btn btn-add-n btn-fill-horz" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit">
        <i class="fa fa-plus" aria-hidden="true"></i> Add new</a>
    @if (Model.Any())
    {
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Benefit)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveStatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActiveClosed)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ModifiedDate)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Benefit.Name)
                        </td>
                        <td>
                            @if (item.ActiveStatus ?? false)
                            {
                                <span class="full-time">Actived</span>
                            }
                            else
                            {
                                <span class="part-time">No actived</span>
                            }
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ActiveDate)
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ActiveClosed)
                        </td>
                        <td>
                            @string.Format("{0:d}", item.ModifiedDate)
                        </td>
                        <td>
                            <ul>
                                <li><a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Edit" asp-route-benefitId="@item.BenefitId" asp-route-companyId="@item.CompanyId" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></li>
                                <li><a asp-area="Employer" asp-controller="CompanyBenefits" asp-action="Delete" asp-route-benefitId="@item.BenefitId" asp-route-companyId="@item.CompanyId" data-ajax="true" data-ajax-method="GET" data-ajax-update="#Outer_CompanyBenefit"><i class="fa fa-trash-o" aria-hidden="true"></i></a></li>
                            </ul>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h4 class="text-gray">No data ..</h4>
    }
</section>